color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.33969291765242815
  lightness: 0.8375929312314838
  saturation: 0.7591016879305243
  rhythmicContrast: 0.6995436053257436
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Domain name market place
layout_spectrum: 0.9117541022133082
typography_spectrum: 0.748539482941851
content: []
title: Mike Han's report for Chinese domain market every week
description: Communicate and help each other understand the market well
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/76798f87-2a9f-4e0f-b5cc-f64391bb0834.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/44a05ccc-9221-45fd-9a00-5b3494c5fae7.png
content_rating:
  adult: false
author:
  name: Mike Han
  email: MichaelB9@yeah.net
analytics:
  twitter: ''
